#!/usr/bin/env bash

set -eo pipefail

if [ "$(uname -s)" = "Darwin" ]; then
    app="/Applications/Inform.app"
    bin="$app/Contents/MacOS"
    lib="$HOME/Library/Inform"
    share="$app/Contents/Resources"
else
    bin="/usr/local/share/inform7/Compilers"
    lib="$HOME/Library/Inform"
    share="/usr/local/share/inform7"
fi

proj="$(dirname $0)/the-archive.inform"

if [ -n "$RELEASE" ]; then
    i6opts="-~kE2~S~Dwv8G"
else
    i6opts="-kE2SDwG"
fi

$bin/ni \
    -internal "$share/Internal" \
    -external "$lib" \
    -project "$proj" \
    -format=ulx

$bin/inform6 \
    $i6opts \
    "+include_path=$share/Library/6.11,.,../Source" \
    "$proj/Build/auto.inf" \
    "$proj/Build/output.ulx"

