#!/usr/bin/env bash

set -eo pipefail

clear

rm -f game.glksaverestore

glulxe "$(dirname $0)/the-archive.inform/Build/output.ulx" <<EOF &
game
look
go north
go west
go door
go south
EOF

# glulxe uses curses, which uses 100% CPU while it polls for input. :(
pid=$!
trap "kill $pid" exit
sleep 1

