name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --tag the-archive-public
      - name: Run tests
        run: docker run --rm the-archive-public
